all:
	g++ --std=c++98 -Wall -Wextra -Wpedantic   -fexceptions -g  -c  class/Buscador.cpp -o  class/Buscador.o
	g++ --std=c++98 -Wall -Wextra -Wpedantic   -fexceptions -g  -c  class/Central.cpp -o  class/Central.o
	g++ --std=c++98 -Wall -Wextra -Wpedantic   -fexceptions -g  -c  class/DatosLlamada.cpp -o  class/DatosLlamada.o
	g++ --std=c++98 -Wall -Wextra -Wpedantic   -fexceptions -g  -c  class/Enlace.cpp -o  class/Enlace.o	
	g++ --std=c++98 -Wall -Wextra -Wpedantic   -fexceptions -g  -c  class/Interfaz.cpp -o  class/Interfaz.o	
	g++ --std=c++98 -Wall -Wextra -Wpedantic   -fexceptions -g  -c  class/Interno.cpp -o  class/Interno.o
	g++ --std=c++98 -Wall -Wextra -Wpedantic   -fexceptions -g  -c  class/LectorArchivos.cpp -o  class/LectorArchivos.o
	g++ --std=c++98 -Wall -Wextra -Wpedantic   -fexceptions -g  -c  class/Llamada.cpp -o  class/Llamada.o
	g++ --std=c++98 -Wall -Wextra -Wpedantic   -fexceptions -g  -c  class/ProcesadorLlamada.cpp -o  class/ProcesadorLlamada.o
	g++ --std=c++98 -Wall -Wextra -Wpedantic   -fexceptions -g  -c  class/Spot.cpp -o  class/Spot.o
	g++ --std=c++98 -Wall -Wextra -Wpedantic   -fexceptions -g  -c  main.cpp -o  main.o
	g++  -o TP2_debug  class/Buscador.o  class/Central.o  class/DatosLlamada.o  class/Enlace.o  class/Interfaz.o  class/Interno.o  class/LectorArchivos.o  class/Llamada.o class/ProcesadorLlamada.o  class/Spot.o  main.o 
