all:
	g++ main.cpp class/LectorArchivos.h class/DatosLlamada.h class/Central.h class/Llamada.h class/Internos.h class/Nodo.h class/Opciones.h class/Enlace.h class/Lista.h class/Menu.h class/ProcesadorLlamada.h -o main -std=c++98 -Wall -Wextra -Wpedantic
