all:
	g++ -Wall -fexceptions -g  -c  class/Buscador.cpp -o  class/Buscador.o
	g++ -Wall -fexceptions -g  -c  class/Central.cpp -o  class/Central.o
	g++ -Wall -fexceptions -g  -c  class/DatosLlamada.cpp -o  class/DatosLlamada.o
	g++ -Wall -fexceptions -g  -c  class/Enlace.cpp -o  class/Enlace.o	
	g++ -Wall -fexceptions -g  -c  class/Interfaz.cpp -o  class/Interfaz.o	
	g++ -Wall -fexceptions -g  -c  class/Interno.cpp -o  class/Interno.o
	g++ -Wall -fexceptions -g  -c  class/LectorArchivos.cpp -o  class/LectorArchivos.o
	g++ -Wall -fexceptions -g  -c  class/Llamada.cpp -o  class/Llamada.o
	g++ -Wall -fexceptions -g  -c  class/Ordenar.cpp -o  class/Ordenar.o
	g++ -Wall -fexceptions -g  -c  class/ProcesadorLlamada.cpp -o  class/ProcesadorLlamada.o
	g++ -Wall -fexceptions -g  -c  class/Spot.cpp -o  class/Spot.o
	g++ -Wall -fexceptions -g  -c  TP2/main.cpp -o  TP2/main.o
	g++  -o TP2_debug  class/Buscador.o  class/Central.o  class/DatosLlamada.o  class/Enlace.o  class/Interfaz.o  class/Interno.o  class/LectorArchivos.o  class/Llamada.o  class/Ordenar.o  class/ProcesadorLlamada.o  class/Spot.o  TP2/main.o 
